apiVersion: v1
kind: Service
metadata:
  name: slsa-simulation-app-svc
  namespace: slsa-simulation
spec:
  type: NodePort
  selector:
    app: slsa-simulation-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080